/**
 * Image sitemap for Google Images discovery.
 *
 * Implemented as a route handler (not a Next.js MetadataRoute.Sitemap) because
 * Next.js's sitemap type does not natively support the Google image-sitemap
 * extension (`<image:image>` element). The main sitemap.xml is generated by
 * app/sitemap.ts and contains URL entries only; this file contains the image
 * entries with proper `<image:loc>` tags.
 */

const baseUrl = 'https://www.ceremonyverse.com'

interface ImageEntry {
  url: string
  images: string[]
}

const entries: ImageEntry[] = [
  {
    url: `${baseUrl}/`,
    images: [
      '/images/hero-lehenga.webp',
      '/images/live-video-shopping-india.webp',
      '/images/services-hero.webp',
    ],
  },
  {
    url: `${baseUrl}/services/`,
    images: ['/images/services-hero.webp'],
  },
  {
    url: `${baseUrl}/buy-bridal-lehenga-from-india-usa/`,
    images: ['/images/hero-lehenga.webp'],
  },
  {
    url: `${baseUrl}/how-it-works/`,
    images: ['/images/live-video-shopping-india.webp'],
  },
]

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

export async function GET(): Promise<Response> {
  const xmlParts: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
  ]

  for (const entry of entries) {
    xmlParts.push('  <url>')
    xmlParts.push(`    <loc>${escapeXml(entry.url)}</loc>`)
    for (const img of entry.images) {
      const imgUrl = img.startsWith('http') ? img : `${baseUrl}${img}`
      xmlParts.push('    <image:image>')
      xmlParts.push(`      <image:loc>${escapeXml(imgUrl)}</image:loc>`)
      xmlParts.push('    </image:image>')
    }
    xmlParts.push('  </url>')
  }

  xmlParts.push('</urlset>')

  return new Response(xmlParts.join('\n'), {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  })
}
