import { MetadataRoute } from "next"

const baseUrl = "https://www.ceremonyverse.com"

type Frequency = "weekly" | "monthly" | "yearly"
type Entry = { path: string; changeFrequency: Frequency; priority: number; lastModified?: Date }

const pages: Entry[] = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/pricing/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/destination-wedding-feasibility-plan/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/destinations/", changeFrequency: "monthly", priority: 0.95 },
  { path: "/destinations/cancun-indian-wedding/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/destinations/riviera-maya-indian-wedding/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/destinations/los-cabos-indian-wedding/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/destinations/punta-cana-indian-wedding/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/resorts/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/resorts/moon-palace-cancun-indian-wedding/", changeFrequency: "monthly", priority: 0.85 },
  { path: "/resorts/lopesan-costa-bavaro-indian-wedding/", changeFrequency: "monthly", priority: 0.85 },
  { path: "/resorts/hard-rock-riviera-maya-indian-wedding/", changeFrequency: "monthly", priority: 0.85 },
  { path: "/resorts/hyatt-inclusive-collection-indian-wedding/", changeFrequency: "monthly", priority: 0.85 },
  { path: "/indian-destination-wedding-cost/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/indian-wedding-room-block-mexico/", changeFrequency: "monthly", priority: 0.85 },
  { path: "/lehenga-for-destination-wedding-mexico/", changeFrequency: "monthly", priority: 0.85 },
  { path: "/about/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/how-it-works/", changeFrequency: "monthly", priority: 0.8, lastModified: new Date("2026-08-21T17:00:00-04:00") },
  { path: "/contact/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/free-guides/", changeFrequency: "weekly", priority: 0.8 },
  { path: "/before-signing-indian-wedding-resort-proposal/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/planning-tools/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/planning-tools/budget/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/planning-tools/shipping-customs/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/planning-tools/resort-comparison/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/planning-tools/family-responsibility-map/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/planning-tools/guest-logistics/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/destination-decision-map/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/", changeFrequency: "weekly", priority: 0.8 },
  { path: "/real-weddings/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/how-to-buy-bridal-lehenga-from-india-to-usa/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/indian-bridal-wear-new-york-new-jersey/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/buy-bridal-lehenga-from-india-usa/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/buy-sherwani-from-india-usa/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/buy-indian-wedding-outfits-from-india/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/indian-wedding-shopping-canada/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/kanchipuram-silk-sarees-usa/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/banarasi-silk-sarees-usa/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/avoid-indian-wedding-shopping-scams/", changeFrequency: "monthly", priority: 0.9 },
  { path: "/services/bridal-lehengas/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/bridesmaid-and-family-outfits-from-india/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/indian-destination-wedding-planner-mexico/", changeFrequency: "monthly", priority: 0.95 },
  { path: "/gujarati-destination-wedding-mexico/", changeFrequency: "monthly", priority: 0.95 },
  { path: "/haldi-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/reception-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/mehndi-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/sangeet-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/baraat-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/gujarati-wedding-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-guest-outfits-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-texas/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-california/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-new-york/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-new-jersey/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-philadelphia/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-massachusetts/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-georgia/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-florida/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-washington-dc/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/indian-wedding-shopping-illinois/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/how-to-plan-gujarati-hindu-destination-wedding-mexico/", changeFrequency: "monthly", priority: 0.8, lastModified: new Date("2026-08-21T10:16:00-04:00") },
  { path: "/blog/mexico-or-punta-cana-indian-destination-wedding/", changeFrequency: "monthly", priority: 0.8, lastModified: new Date("2026-08-21T10:37:00-04:00") },
  { path: "/blog/ordering-indian-wedding-outfits-usa-canada/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/how-to-take-lehenga-measurements-at-home/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/mexico-wedding-wardrobe-sourcing-from-india/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/how-to-choose-indian-wedding-jewelry-usa/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/how-to-buy-authentic-kanchipuram-silk-sarees-online-usa/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/custom-sherwani-sizing-guide-india-usa/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/indian-wedding-return-gifts-bulk-usa/", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/indian-wedding-outfit-scams-nri-brides/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/indian-wedding-outfit-checklist-every-ceremony/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/how-much-does-bridal-lehenga-cost-india-2026/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/how-to-coordinate-bridesmaid-lehengas-india-usa/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/shipping-indian-wedding-outfits-usa-customs-duties/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/when-to-order-indian-wedding-outfits-nri-bride/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/nri-bride-lehenga-sourcing-new-jersey-story/", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/nri-wedding-planning-timeline/", changeFrequency: "monthly", priority: 0.6 },
  { path: "/blog/gujarati-wedding-outfit-guide/", changeFrequency: "monthly", priority: 0.6 },
  { path: "/blog/us-tariffs-indian-wedding-outfits-2026/", changeFrequency: "monthly", priority: 0.6 },
  { path: "/faq/", changeFrequency: "monthly", priority: 0.6 },
  { path: "/privacy/", changeFrequency: "yearly", priority: 0.4 },
]

export default function sitemap(): MetadataRoute.Sitemap {
  return pages.map(({ path, ...entry }) => ({
    url: `${baseUrl}${path}`,
    ...entry,
  }))
}
