import type { EditorialGuideData } from "@/components/editorial-guide"

export const mexicoCompleteGuide: EditorialGuideData = {
  title: "Indian Destination Wedding in Mexico: Costs, Resorts & a Four-Day Plan",
  description: "Plan a Gujarati or Hindu wedding in Mexico with transparent planning fees, a four-day schedule, resort comparisons, Indian catering questions, mandap logistics and guest travel decisions.",
  path: "/blog/indian-destination-wedding-mexico-complete-guide/",
  published: "2026-09-13T12:00:00Z",
  modified: "2026-09-13T12:00:00Z",
  intro: "An Indian destination wedding in Mexico works when the resort, event schedule, Hindu ceremony requirements, food plan, guest rooms, and complete budget fit together. Start with the people and celebrations you want to include, then compare written resort proposals. CeremonyVerse offers a free first consultation, an optional $300 Feasibility Plan, and planning packages starting at $4,000, $5,500, and $8,000.",
  sections: [
    {id:"first-decisions",title:"Start with five decisions before choosing a resort",paragraphs:[
      "Write down your likely guest range, preferred month, must-have celebrations, host spending limit, and who is paying for guest travel. Those five decisions are more useful than a list of attractive resorts. A 100-person wedding with four private events creates a different brief from a 200-person wedding with two events, even if both families choose the same hotel. Use a low and high attendance estimate until invited households have discussed the trip. Interest in attending is not the same as a booked room.",
      "For a Gujarati or Hindu celebration, ask the couple and their parents which traditions must be protected. Some families want separate Graha Shanti, Pithi, Mehndi, Garba, and wedding events; others combine gatherings. Do not turn one sample itinerary into a rule for every family. Record the priest's requirements and the family's preferred explanations, procession, meal timing, and ceremony duration. Choose one family decision contact on each side so the resort receives a single approved brief instead of several conflicting messages. Keep the written brief short enough that everyone can actually use it."
    ],links:[{label:"Gujarati wedding planning in Mexico",href:"/gujarati-destination-wedding-mexico/"},{label:"Compare planning packages",href:"/indian-destination-wedding-planner-mexico/"}]},
    {id:"planning-fees",title:"Planning fees and resort package prices are different",paragraphs:[
      "CeremonyVerse's Event Coordination & Management starts at $4,000 USD for couples handing over finalized plans, contracts, and vendors. Partial Planning & Coordination starts at $5,500 for couples with a venue and initial vendors who need help completing the remaining work. Full Planning & Design starts at $8,000 for support from the beginning, including venue and vendor coordination, progress meetings, and management of the agreed events. The final written proposal defines the dates, team, on-site scope, and any additional staffing or travel.",
      "The optional $300 Feasibility & Action Plan is a smaller first commitment. It includes a 60-minute working session, review of the budget and guest-cost worksheets, up to two current proposals if available, a written action brief, and a 20-minute follow-up. It is not a resort quote or a booking service. If you sign a CeremonyVerse planning contract within 30 days after delivery, the $300 is credited toward the planning service fee. The plan is non-refundable once work begins. Your first 30-minute introductory consultation remains free, and no paid plan is required to ask whether the service fits."
    ],links:[{label:"Full pricing, inclusions and exclusions",href:"/pricing/"},{label:"What the $300 plan delivers",href:"/destination-wedding-feasibility-plan/"}]},
    {id:"complete-cost",title:"Build the complete host budget",paragraphs:[
      "Separate the host budget into resort events, planning, décor and production, other vendors, host-paid travel, outfits, and a reserve. Put the room block in its own section because a family may be responsible for a contractual room commitment even when guests pay for their individual stays. Identify which lines include tax and service charges. A line called reception should explain the guest count, menu, bar, event hours, chairs, linens, venue, and equipment. Without that detail, two quotes with the same number may buy quite different celebrations.",
      "A useful arithmetic example is $25,000 in fixed event costs plus $250 per guest across the chosen private events, an $8,000 starting planning fee, and a 15% reserve. At 100 guests that equals $66,700; at 200 guests it equals $95,450. These are examples using invented inputs, not market averages or resort quotes. They exclude rooms, flights, outfits, planner travel and lodging, and airport transfers. Replace every input with current written information before using the total to make a commitment. If the family will cover a week's travel for grandparents or other VIPs, add it before deciding the event budget is affordable."
    ],links:[{label:"Free destination wedding cost calculator",href:"/planning-tools/budget/"},{label:"The complete-cost guide",href:"/indian-destination-wedding-cost/"}]},
    {id:"package-benchmark",title:"Use published resort packages as a starting benchmark",paragraphs:[
      "Hyatt Inclusive Collection's official South Asian offer currently lists Dulha & Dulhan from $12,295 USD for up to 79 guests, subject to the participating property's terms. The page requires at least 25 rooms for three nights, or 75 cumulative room nights, and says added guests and customizations vary by resort. That is useful starting evidence, but it does not mean that 100 or 200 guests can receive the same celebration at the advertised amount. Nor does it establish that every room, vendor, extra event, or family tradition is included.",
      "Record the package name, publication date, included guest count, event list, hours, and room-night conditions beside the price. Then request a second column showing the additions for your actual wedding. Ask whether a stand-alone Haldi, a longer Garba night, upgraded mandap, outside photographer, additional technicians, or late-night food creates a new line. Avoid subtracting promotional credits until the resort confirms your eligibility and the exact categories on which they may be used. Treat every blank amount as a question to resolve rather than a zero. Keep the original proposal and each revision so the family can see why a total changed."
    ],links:[{label:"Hyatt resort evaluation profile",href:"/resorts/hyatt-inclusive-collection-indian-wedding/"},{label:"Compare resort proposals",href:"/planning-tools/resort-comparison/"}]},
    {id:"resort-shortlist",title:"Which resorts are worth comparing for Gujarati and Hindu weddings?",paragraphs:[
      "Build a shortlist around verified requirements rather than a universal best-resort ranking. Moon Palace Cancun is an option to evaluate for families comparing several event spaces and group conditions. Its public wedding page lists different venue capacities depending on whether the setup is a cocktail reception, buffet, or ceremony; a maximum occupancy number should therefore never be copied into a seated wedding plan. Hard Rock Riviera Maya is another property families can ask us to evaluate for their event program, guest access, production needs, and current contract terms.",
      "Participating Hyatt Inclusive Collection properties provide another comparison route through their published South Asian program. For each property, request a venue map and a layout for your actual guest count, stage, dance floor, food stations, service aisles, and mandap. Ask how many weddings can operate on the same dates, how rehearsal access works, and whether every outdoor event has an indoor alternative. Inclusion in a CeremonyVerse comparison does not imply a preferred-vendor relationship or availability. The right shortlist may be only two properties if a longer list would create more decisions without solving your family’s constraints."
    ],links:[{label:"Moon Palace Cancun profile",href:"/resorts/moon-palace-cancun-indian-wedding/"},{label:"Hard Rock Riviera Maya profile",href:"/resorts/hard-rock-riviera-maya-indian-wedding/"},{label:"All resort profiles",href:"/resorts/"}]},
    {id:"regions",title:"Cancún, Riviera Maya, Los Cabos or Puerto Vallarta?",paragraphs:[
      "Choose the region using the guest map, event requirements, and resort proposals. Compare the airports from which your largest guest groups would depart, whether the trip needs a connection, arrival times, and the transfer to the actual hotel. Do not assign a standard transfer time to an entire region. An attractive room rate can lose its advantage if the family must subsidize difficult flights or arrange several additional transfer windows. Older guests, children, wedding luggage, and mobility needs should be part of this comparison from the beginning.",
      "Cancún and Riviera Maya can be compared together while keeping each property's distance, layout, and policies distinct. Los Cabos and the Puerto Vallarta area deserve their own guest and supplier checks. A vendor's Mexican Caribbean experience does not automatically mean a local team is available on the Pacific coast. Ask who would travel, how equipment would move, and who handles contingency arrangements if a provider is delayed. If Punta Cana or Jamaica is still being considered, use the same guest range and event list there too. Changing the destination and simplifying the wedding at the same time makes the prices difficult to compare fairly."
    ],links:[{label:"Cancún",href:"/destinations/cancun-indian-wedding/"},{label:"Riviera Maya",href:"/destinations/riviera-maya-indian-wedding/"},{label:"Los Cabos",href:"/destinations/los-cabos-indian-wedding/"},{label:"Puerto Vallarta planning guide",href:"/blog/indian-destination-wedding-puerto-vallarta/"}]},
    {id:"four-day-schedule",title:"A practical four-day Indian wedding schedule",paragraphs:[
      "Day one can focus on arrivals, a relaxed welcome meal, and Mehndi for the people who need it. Keep the first formal event late enough for the main arrival groups, but do not assume all guests will arrive on time. Give the bridal Mehndi appointment its own quiet space and realistic duration. Guests who arrive early should know where to go, where they can eat, and whether room access is available. A welcome gathering should help everyone settle in without making the couple responsible for individual airport updates.",
      "Day two can hold Haldi or Pithi in the morning, a recovery period and lunch, then Sangeet or Garba in the evening. Day three can hold the Baraat, Hindu ceremony, and a reception with a genuine rest and outfit-change interval. Day four can be a farewell breakfast and staggered departures. This is only a sample. Some families prefer the ceremony and reception on different days, while others need extra Vidhi time or a smaller separate religious gathering. Map each event to its own venue, food, guest count, sound requirements, setup window, and rain location. A four-day stay does not always mean four private events, and the contract should count the events exactly as the resort prices them."
    ]},
    {id:"ceremony",title:"Protect the Hindu ceremony and the Baraat",paragraphs:[
      "Ask the family's pandit to give a written ceremony outline early. Confirm the intended duration, language explanations, family participants, seating, shade, water, sound, and any items that must be prepared in advance. Gujarati traditions vary by family, so the couple should approve the outline instead of relying on a generic ritual checklist. For the Baraat, agree on the gathering place, route, arrival sequence, accessible alternative, music arrangements, and the moment when the procession needs to finish so the ceremony can start comfortably.",
      "The resort must separately approve anything involving fire, a structure, power, a vehicle, animals, or special effects. A South Asian package name does not grant every permission. Send the actual ceremony and production requirements for review, then retain the written response with the event brief. Assign who brings the puja items and who verifies the list with the pandit on arrival. Do not assume that specialty food, plants, seeds, or other ceremonial materials can be packed or shipped across a border without checking official requirements. Where a required item cannot travel or be used, discuss an acceptable alternative with the pandit and the family before the wedding week."
    ]},
    {id:"food",title:"Indian catering, Jain meals and outside chefs",paragraphs:[
      "Start the food conversation with menus and preparation requirements, not the phrase Indian food available. Specify the event, meal, dishes, ingredients, service style, and dietary requirements. Ask each household with restrictions what those restrictions mean for them. Jain, vegetarian, vegan, satvik, and allergy requirements should not be treated as interchangeable labels. If a family needs separate cookware, preparation surfaces, frying oil, or utensils, ask the culinary team to confirm those procedures. An Indian restaurant at a resort does not by itself establish how a private wedding menu will be produced.",
      "There are three practical paths to investigate: the resort kitchen prepares the approved menu, an outside specialist advises or collaborates with that kitchen, or an external caterer works under the resort's explicit permission. Do not promise the third route before approval. Ask about kitchen access, staffing, food sourcing, health documentation, liability, equipment, supervision fees, and service responsibility. A tasting should check the actual agreed dishes and the preparation process as far as the resort can demonstrate it. Record the final menu with clear labels for guest service. CeremonyVerse coordinates questions and decisions within its planning scope; the resort and responsible food provider must confirm what they can safely supply."
    ],links:[{label:"Outside-chef and Indian catering guide",href:"/blog/indian-wedding-catering-mexico-all-inclusive-resorts/"}]},
    {id:"live-stations",title:"Plan live chaat, sweets and late-night food as real services",paragraphs:[
      "A live chaat or dosa station requires more than adding a dish name to a menu. Ask where it will operate, how guests will queue, who staffs it, what ingredients are prepared in advance, and what power or cooking equipment it needs. Confirm whether outdoor conditions affect preparation or service. Keep hot cooking areas and service queues clear of Garba circles, performance access, and guest walkways. For sweets, prasad, or an eggless cake, identify the supplier and the resort's approval process rather than assuming a family delivery can be brought straight into the ballroom.",
      "Late-night food needs an agreed serving window and guest count. If the reception ends after the resort's usual outlets close, explain the actual option to guests instead of promising that all-inclusive dining means every meal is available at any hour. Put service staff, cleanup, equipment, and tax treatment in the quote. Ask what happens if the Sangeet runs late or fewer people attend. These details are small compared with the overall wedding decision, but they often determine whether the evening feels relaxed or hurried. Use one approved food schedule shared with the kitchen, event team, DJ, and family contact."
    ]},
    {id:"mandap-production",title:"Mandap, décor, sound and production vendors",paragraphs:[
      "Request an itemized décor and production proposal. Separate design, structures, flowers, furniture, transport, installation, technicians, power, lighting, and removal. A rendering shows the visual idea; it does not confirm that the structure is approved for the venue or that installation labor is included. Ask who provides the method for securing the mandap, which surfaces may be used, and who signs off on the setup. If décor will move between the ceremony and reception, allow time for the team to dismantle, move, and reset it without rushing through guests.",
      "For sound, list the real uses: pandit microphone, family readings, Baraat music, Sangeet tracks, live performances, speeches, and reception dancing. Identify backup microphones and the person who can resolve a sound failure. Request sound-check access before guests arrive. Confirm the outside-vendor rules for each company and each event day, including day passes, meals, storage, security, and equipment access. Do not accept an assurance that a vendor has worked at the brand before as permission for the exact property. The selected vendor, date, crew, and equipment plan should be approved together."
    ],links:[{label:"Hidden resort fees checklist",href:"/blog/hidden-resort-fees-4-day-indian-wedding-cancun/"}]},
    {id:"room-blocks",title:"Room blocks and the guest commitment",paragraphs:[
      "Before signing a room block, compare the family's expected attendance with the contract's minimum rooms and nights. Ask when rooms can be released, which bookings count toward the group, what happens after the deadline, and who is responsible for any shortfall. Complimentary rooms or private-event benefits can depend on actual qualifying room nights. A quoted benefit is not earned simply because the invitation list is large. Keep room-block decisions with the person authorized to accept the financial obligation and have unclear legal terms reviewed by an appropriate professional.",
      "Tell guests how to book, the relevant deadline, what is included, and whom to contact for booking questions. Explain any event-access restriction for people staying elsewhere before they choose another hotel. Track arrivals and room status in a private working list, sharing only what each provider needs. Avoid putting passport details or sensitive documents in a group chat. Have a process for roommates, children, accessibility requests, cancellations, and missed connections. CeremonyVerse can organize the guest information and responsibilities included in the signed scope, while the named travel provider and resort control their booking, payment, and contract terms."
    ],links:[{label:"Mexico wedding room-block guide",href:"/indian-wedding-room-block-mexico/"},{label:"Guest and VIP travel worksheet",href:"/planning-tools/guest-logistics/"}]},
    {id:"outfits",title:"Coordinate India outfits with the wedding calendar",paragraphs:[
      "Build the outfit list around the approved ceremonies, setting, and change intervals. The bride and groom may need different footwear, jewelry, layers, and practical accessories for an outdoor Haldi, a long ceremony, and an evening reception. Coordinate the wedding party with a clear color reference, spending range, measurement deadline, and delivery destination. Do not request everyone to make a purchase until the group understands who is responsible for alterations, shipping, and customs charges. Separate the outfit budget from the planning service fee so the family can compare total spending honestly.",
      "Work backward from a local fitting and alteration buffer, not only from the flight date. Request current production and shipping estimates for the actual order, record approved fabrics and work, and ask for available pre-shipment checks. A photo or video can help identify visible differences but does not remove every risk of a remote custom order. Keep essential wedding pieces accessible during travel according to the carrier's baggage rules. If CeremonyVerse's paid India sourcing is selected, align the written shopping brief with the event plan while keeping that service's products, shipping, taxes, and alterations separately itemized."
    ],links:[{label:"When to order Indian wedding outfits",href:"/blog/when-to-order-indian-wedding-outfits-nri-bride/"},{label:"India sourcing services",href:"/buy-indian-wedding-outfits-from-india/"}]},
    {id:"rain-backup",title:"Rain backup, guest comfort and the wedding week",paragraphs:[
      "An indoor backup should be a confirmed plan, not a sentence saying subject to availability. Ask which space is held, whether it fits the actual seated or performance layout, who makes the weather decision, and the deadline for that decision. Establish any move fee, extra labor, sound restrictions, and guest communication process. Discuss shade and heat as well as rain. Older guests may need shorter walking routes, nearby restrooms, seating during the Baraat, and a quiet place between events. Ask the property about those needs before promising a smooth guest experience.",
      "In the final planning stage, issue one version-controlled schedule showing event owners and essential contacts. Give vendors the operational detail they need, and guests a simpler version with times, locations, attire, and assistance contacts. Mark which family member can approve an extra cost and which decisions must come back to the couple. Leave reasonable transition time rather than scheduling every minute with an activity. The goal is to make the couple's wedding week easier, with questions routed to the right person instead of repeatedly reaching the bride or groom while they are dressing or participating in a ceremony."
    ]},
    {id:"next-step",title:"What to bring to your free consultation",paragraphs:[
      "Bring an approximate guest count, a preferred month or date range, the celebrations you want, and a budget that states what it must cover. If you already have a resort proposal, bring it with its exclusions and room-block conditions. You do not need polished spreadsheets or a final guest list for the first conversation. Mini can use the free 30-minute call to understand the wedding, explain CeremonyVerse's available support, and identify the next decision. A requested call is not booked until a time has been agreed directly.",
      "If the main uncertainty is whether the destination, budget, and rituals fit together, consider the $300 written Feasibility Plan before a larger planning commitment. If the venue and vendors are already selected, coordination may be the better conversation. If you want help developing the whole wedding, review the full planning scope. The choice should reflect what remains to be done, not pressure to choose the largest package. Keep asking the practical question: what decision will this service help us make, who will do the work, and what will we receive in writing?"
    ],links:[{label:"Book a Free Consultation",href:"/contact/?service=mexico&from=mexico-complete-guide"},{label:"Start with the $300 Feasibility Plan",href:"/destination-wedding-feasibility-plan/"}]}
  ],
  faqs:[
    {question:"How much does CeremonyVerse charge for a Mexico Indian wedding?",answer:"Planning starts at $4,000 for event coordination, $5,500 for partial planning, and $8,000 for full planning and design. The optional Feasibility Plan is $300. These are service fees; resort events, rooms, vendors, travel, outfits, and other third-party charges are separate. The first 30-minute consultation is free."},
    {question:"Can we plan four days of Hindu wedding events at one all-inclusive resort?",answer:"It may be possible when the property confirms each event's venue, hours, guest capacity, menu, cultural requirements, production rules, room conditions, and rain backup. A four-day stay does not establish how many private events are included. Request a separate line for each celebration."},
    {question:"Which Mexico resort is best for a Gujarati wedding?",answer:"There is no universal best resort. Compare the family's guest map, room budget, rituals, vegetarian or Jain requirements, Garba space, mandap and fire permissions, and indoor alternatives against the exact property's current proposal."},
    {question:"Can a resort allow an outside Indian chef?",answer:"Only the property can approve that arrangement. Ask whether the chef can work in the resort kitchen, advise its culinary team, or provide catering under a permitted external arrangement. Confirm food sourcing, staffing, equipment, health documentation, supervision, fees, and responsibilities before contracting."},
    {question:"Is the $300 Feasibility Plan required before full planning?",answer:"No. It is an optional written decision service after the free introductory call. Its fee is credited toward a CeremonyVerse planning service fee if the planning contract is signed within 30 days after the written plan is delivered. It is non-refundable once work begins."}
  ],
  sources:[
    {label:"Hyatt Inclusive Collection: South Asian package and conditions",href:"https://www.hyattinclusivecollection.com/en/special-offers/south-asian-weddings/"},
    {label:"Moon Palace Cancun: wedding venues and packages",href:"https://www.moonpalacecancun.com/weddings"},
    {label:"CeremonyVerse: published planning and sourcing fees",href:"https://www.ceremonyverse.com/pricing/"}
  ]
}
